import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { server } from "../config/index";

export async function getServerSideProps(context) {
  const res = await fetch(`${server}/api/issues`);

  const data = await res.json();

  return {
    props: { data },
  };
}

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Github issues application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Find Random GitHub issues</h1>

      <div>
        <p>Name :{props.data.name}</p>
        <p>Author :{props.data.author}</p>
        <p>Labels : {props.data.labels.join(", ")}</p>
        <a href={props.data.url}>URL: Link to the issue</a>
      </div>

      <footer className={styles.footer}>
        <p
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Mrinmay Santra
        </p>
      </footer>
    </div>
  );
}
